apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-pgsql
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
      storage: 8Gi
  hostPath: 
    path: "/opt/sonar/pgsql"
    type: DirectoryOrCreate